name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - run: |
          pwd
          ls
      - uses: actions/checkout@v2.0.0
      - run: |
          pwd
          ls
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Print built files
        run: find dist
